server:
  port: 8090
application:
  login:
  password:
  lottery-url: https://demo.reunico.com/meetup/api/lottery
  participant-url: https://demo.reunico.com/meetup/api/registered-participants
  numbering-url: https://demo.reunico.com/meetup/api/numbering
  notify-url: https://demo.reunico.com/meetup/api/notify-participant
camunda:
  bpm:
    client:
      base-url: http://localhost:8080/engine-rest
