### Создать план миграции
POST {{url}}/engine-rest/migration/generate
Content-Type: application/json

{
  "sourceProcessDefinitionId": "{{sourceDefinitionId}}",
  "targetProcessDefinitionId": "{{targetDefinitionId}}",
  "variables": {
    "acme": {
      "type": "String",
      "value": "Test"
    }
  }
}

> {%
client.global.set("migrationPlan", response.body.toString())
 %}
